version: "3"
services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db:27017/your_database_name
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
