version: "3"
services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - backend/.env
